version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: pg
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
